# NOTE: update this with your service name
service: projectManagement

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-west-2:*:*"


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  createUser:
    handler: createUser.main
    events:
      - http:
          path: createUser
          method: post
          cors: true
          authorizer: aws_iam

  deleteUser:
    handler: deleteUser.main
    events:
      - http:
          path: deleteUser/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  updateUser:
    handler: updateUser.main
    events:
    - http:
        path: updateUser/{id}
        method: put
        cors: true
        authorizer: aws_iam

  getUser:
    handler: getUser.main
    events:
    - http:
        path: getUser/{id}
        method: get
        cors: true
        authorizer: aws_iam